export const CONSTANTS = {
    PREV: 'prev',
    NEXT: 'next',
    GET_POKEMONS: 'GET_POKEMONS',
    GET_POKEMONS_LOADING: 'GET_POKEMONS_LOADING',
    GET_NEXT_PAGE_POKEMONS: 'GET_NEXT_PAGE_POKEMONS',
    GET_PREV_PAGE_POKEMONS: 'GET_PREV_PAGE_POKEMONS',
    GET_COUNT_POKEMONS: 'GET_COUNT_POKEMONS',
};